// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_maquinistas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_maquinistas_default = defineTool({
  name: "list_maquinistas",
  title: "Listar maquinistas",
  description: "Devuelve los maquinistas visibles para el usuario autenticado (respeta RLS y bases asignadas). Filtro opcional por base y por estado activo.",
  inputSchema: {
    base: z.string().optional().describe("Nombre de la base (opcional)."),
    activo: z.boolean().optional().describe("Filtrar por activo/inactivo."),
    limit: z.number().int().positive().max(500).optional().describe("M\xE1ximo de filas (por defecto 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ base, activo, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb(ctx).from("maquinistas").select("id, matricula, nombre, apellidos, base, activo, fecha_primer_servicio, bajo_pe_1603").order("apellidos", { ascending: true }).limit(limit ?? 100);
    if (base) q = q.eq("base", base);
    if (typeof activo === "boolean") q = q.eq("activo", activo);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { maquinistas: data }
    };
  }
});

// src/lib/mcp/tools/get_maquinista.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_maquinista_default = defineTool2({
  name: "get_maquinista",
  title: "Detalle de un maquinista",
  description: "Devuelve la ficha completa de un maquinista por id o matr\xEDcula, incluyendo sus certificaciones vigentes y su expediente PE 16.03 y PE 12.01 abiertos si existen.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("UUID del maquinista."),
    matricula: z2.string().optional().describe("Matr\xEDcula del maquinista (alternativa a id).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, matricula }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    if (!id && !matricula) {
      return { content: [{ type: "text", text: "Debes indicar id o matr\xEDcula" }], isError: true };
    }
    const client = sb2(ctx);
    let mq = client.from("maquinistas").select("*").limit(1);
    if (id) mq = mq.eq("id", id);
    else mq = mq.eq("matricula", matricula);
    const { data: maquinistas, error } = await mq;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const maquinista = maquinistas?.[0];
    if (!maquinista) return { content: [{ type: "text", text: "No encontrado" }], isError: true };
    const [certs, e1603, e1201] = await Promise.all([
      client.from("maquinista_certificaciones").select("*").eq("maquinista_id", maquinista.id),
      client.from("expedientes_1603").select("*").eq("maquinista_id", maquinista.id).eq("estado", "abierto"),
      client.from("expedientes_1201").select("*").eq("maquinista_id", maquinista.id).eq("estado", "Abierta")
    ]);
    const payload = {
      maquinista,
      certificaciones: certs.data ?? [],
      expedientes_1603_abiertos: e1603.data ?? [],
      expedientes_1201_abiertos: e1201.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_alertas_certificaciones.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_alertas_certificaciones_default = defineTool3({
  name: "list_alertas_certificaciones",
  title: "Alertas de certificaciones",
  description: "Devuelve las certificaciones de maquinistas pr\xF3ximas a vencer o vencidas (por inactividad), respetando las bases visibles para el usuario.",
  inputSchema: {
    base: z3.string().optional().describe("Filtrar por base."),
    dias: z3.number().int().positive().max(365).optional().describe("Ventana en d\xEDas para 'pr\xF3xima a vencer' (por defecto 90).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ base, dias }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const client = sb3(ctx);
    const ventanaDias = dias ?? 90;
    let q = client.from("maquinista_certificaciones").select(
      "id, maquinista_id, certificacion_id, base_id, fecha_ultimo_servicio, periodo_inactividad_meses, vigilar_vencimiento, estado, maquinistas!inner(nombre, apellidos, matricula, base, activo), certificaciones(nombre, tipo)"
    ).eq("vigilar_vencimiento", true).eq("maquinistas.activo", true);
    if (base) q = q.eq("maquinistas.base", base);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const hoy = /* @__PURE__ */ new Date();
    const alertas = (data ?? []).map((r) => {
      if (!r.fecha_ultimo_servicio) return null;
      const meses = r.periodo_inactividad_meses ?? 12;
      const fVenc = new Date(r.fecha_ultimo_servicio);
      fVenc.setMonth(fVenc.getMonth() + meses);
      const diasRest = Math.ceil((fVenc.getTime() - hoy.getTime()) / 864e5);
      return {
        maquinista: `${r.maquinistas?.apellidos ?? ""}, ${r.maquinistas?.nombre ?? ""}`.trim(),
        matricula: r.maquinistas?.matricula,
        base: r.maquinistas?.base,
        certificacion: r.certificaciones?.nombre,
        tipo: r.certificaciones?.tipo,
        fecha_ultimo_servicio: r.fecha_ultimo_servicio,
        fecha_estimada_vencimiento: fVenc.toISOString().slice(0, 10),
        dias_restantes: diasRest,
        estado: diasRest < 0 ? "Vencida" : diasRest <= ventanaDias ? "Pr\xF3xima a vencer" : "Vigente"
      };
    }).filter((x) => x && (x.estado === "Vencida" || x.estado === "Pr\xF3xima a vencer")).sort((a, b) => a.dias_restantes - b.dias_restantes);
    return {
      content: [{ type: "text", text: JSON.stringify(alertas) }],
      structuredContent: { alertas }
    };
  }
});

// src/lib/mcp/tools/list_expedientes_1603.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_expedientes_1603_default = defineTool4({
  name: "list_expedientes_1603",
  title: "Expedientes PE 16.03",
  description: "Lista expedientes PE 16.03 (nuevo acceso). Filtro opcional por base y estado.",
  inputSchema: {
    base: z4.string().optional(),
    estado: z4.string().optional().describe("Ej: 'abierto' o 'cerrado'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ base, estado }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    let q = sb4(ctx).from("expedientes_1603").select("id, maquinista_id, fecha_primer_servicio, fecha_inicio, fecha_fin_prevista, estado, maquinistas!inner(nombre, apellidos, matricula, base)").order("fecha_fin_prevista", { ascending: true });
    if (estado) q = q.eq("estado", estado);
    if (base) q = q.eq("maquinistas.base", base);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { expedientes: data } };
  }
});

// src/lib/mcp/tools/list_expedientes_1201.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z5 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_expedientes_1201_default = defineTool5({
  name: "list_expedientes_1201",
  title: "Expedientes PE 12.01",
  description: "Lista fichas PE 12.01 (factor humano). Filtro opcional por base y estado.",
  inputSchema: {
    base: z5.string().optional(),
    estado: z5.string().optional().describe("Ej: 'Abierta' o 'Cerrada'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ base, estado }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    let q = sb5(ctx).from("expedientes_1201").select("id, maquinista_id, id_suceso, fecha_suceso, fecha_primer_servicio, fecha_fin_prevista, estado, maquinistas!inner(nombre, apellidos, matricula, base)").order("fecha_fin_prevista", { ascending: true });
    if (estado) q = q.eq("estado", estado);
    if (base) q = q.eq("maquinistas.base", base);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { expedientes: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fiexmmkokvmpguzevcnb";
var mcp_default = defineMcp({
  name: "gesbase-mcp",
  title: "GesBase \u2014 Renfe SGS",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura sobre GesBase (Renfe Viajeros): maquinistas, alertas de certificaciones, expedientes PE 16.03 y PE 12.01. Todas las llamadas se ejecutan con la identidad del usuario autenticado y respetan las bases y roles asignados (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_maquinistas_default,
    get_maquinista_default,
    list_alertas_certificaciones_default,
    list_expedientes_1603_default,
    list_expedientes_1201_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
